# Generated by Django 5.0.2 on 2024-04-17 13:40

import administracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='bornOn',
            field=models.DateField(validators=[administracion.models.validate_born_on]),
        ),
    ]
